### ISSUE TITLE
How get stdout with unarchive ？

### ISSUE THREAD

**Issue by X-Mars** [seantis/suitable#30]
hello sir,
       
I want get stdout when use unarchive .

It's can got stdout when I use command.

        def get_server_info(self):
              hostname = self.Ansible_api.command('hostname').stdout()
              print(hostname)
              stdout_dict = {}
              stdout_dict['hostname'] = self.hostname_full
              stdout_dict['get_server_info'] = hostname

              self.stdout.append(stdout_dict)

It's can got stdout when I use unarchive. 
```
           def copy_k8s_zip(self):
               stdout = self.Ansible_api.unarchive(src="/Users/mars/Downloads/k8s.zip", dest="/root", copy="yes", owne="sa")
               print(stdout)
               print(stdout.stdout())
```
           prints :  {'contacted': {}}
```
Internal Server Error: /api/action/
Traceback (most recent call last):
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mars/PycharmProjects/vdMaster/action/views.py", line 19, in create
    A.copy_k8s_zip()
  File "/Users/mars/PycharmProjects/vdMaster/action/ansible_api.py", line 49, in copy_k8s_zip
    print(stdout.stdout())
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/suitable/runner_results.py", line 17, in <lambda>
    return lambda server=None: self.acquire(server, key)
  File "/Users/mars/PycharmProjects/vdMaster/venv/lib/python3.6/site-packages/suitable/runner_results.py", line 27, in acquire
    raise KeyError("{} could not be contacted".format(server))
KeyError: 'None could not be contacted'
[20/Aug/2019 14:30:20] "POST /api/action/ HTTP/1.0" 500 17557
```

I hope I can get your reply.

Thank you for your selfless dedication

Your Mars

**Comment by href** [comment]
I think your problem lies with how you define `Ansible_api`.

This indicates that you did not specify a server to connect to:
`KeyError: 'None could not be contacted'`

First you probably want to check if you can connect to your server:
`ssh your-server`

Then you can try doing the same with Suitable:

```python
from suitable import Api
api = Api('your-server')
result = api.command('whoami')
print(result.stdout())
```

If this works, you can try the following, to check if unarchive works:

```python
from suitable import Api
api = Api('your-hostname')
result = api.unarchive(src="/Users/mars/Downloads/k8s.zip", dest="/root", copy="yes", owner="sa")
print(result.stdout())
```

**Comment by X-Mars** [comment]
Thank you very much for your reply.

It's my code error. Now close it.

Wish you good luck.
