### ISSUE TITLE
failed to connect using password

### ISSUE THREAD

**Issue by pingz** [seantis/suitable#4]
I just run one liner to test, and failed to get it work:

`suitable.Api('hostname', remote_user='username', remote_pass='password',).command('whoami').stdout()`

After using `print(result['msg'])` to display whole ssh connection output, I found there is no password at all.

> debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pingz/venv/ansible/local/lib/python2.7/site-packages/suitable/module_runner.py", line 137, in execute
    return self.evaluate_results(callback)
  File "/home/pingz/venv/ansible/local/lib/python2.7/site-packages/suitable/module_runner.py", line 166, in evaluate_results
    self, server
  File "/home/pingz/venv/ansible/local/lib/python2.7/site-packages/suitable/module_runner.py", line 146, in trigger_event
    action = getattr(self.api, method)(*args)
  File "/home/pingz/venv/ansible/local/lib/python2.7/site-packages/suitable/api.py", line 163, in on_unreachable_host
    raise UnreachableError(module, host)
suitable.errors.UnreachableError: [my.host.ip.addr] could not be reached

**Comment by href** [comment]
This did indeed not work :sweat:. The problem was that the password was not passed to Ansible. I don't use password-based ssh, so I didn't test for this. It used to work, but with Ansible 2.x the API changed and I did not properly re-implement this feature.

Anyway, the problem is now fixed and there's a new release on PyPI:
https://pypi.python.org/pypi/suitable/0.7.3

If you run `pip install suitable --upgrade` and re-run your one-liner you should see a different result. If not, don't hesitate to re-open this issue.
