### ISSUE TITLE
2.4+ incompatibilities with module_loader

### ISSUE THREAD

**Issue by jctanner** [seantis/suitable#8]
```$ python -c 'from suitable import Api'                                                   
Traceback (most recent call last):                            
  File "<string>", line 1, in <module>                        
  File "/home/jtanner/.local/lib/python2.7/site-packages/suitable/__init__.py", line 1, in <module>                          
    from suitable.api import Api                              
  File "/home/jtanner/.local/lib/python2.7/site-packages/suitable/api.py", line 5, in <module>                               
    from ansible.plugins import module_loader                 
ImportError: cannot import name module_loader 
```

**Comment by bcoca** [comment]
import has moved
`from ansible.plugins.loader import module_loader `

also, we are planning many changes to plugin loader soon, the API might not look anything like it does now.

**Comment by href** [comment]
Thank ya'll for the heads-up! I published a new Suitable release that is compatible with Ansible 2.4.
